update "DATAMART".genre set classification = 'MOODS' where genre_name = '1980s';
update "DATAMART".genre set classification = 'MOODS' where genre_name = '1990''s';
update "DATAMART".genre set classification = 'DIMENSIONS' where genre_name = '2.5D';
update "DATAMART".genre set classification = 'DIMENSIONS' where genre_name = '2D';
update "DATAMART".genre set classification = 'GENRE' where genre_name = '2D Fighter';
update "DATAMART".genre set classification = 'GENRE' where genre_name = '2D Platformer';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = '360 Video';
update "DATAMART".genre set classification = 'DIMENSIONS' where genre_name = '3D';
update "DATAMART".genre set classification = 'GENRE' where genre_name = '3D Fighter';
update "DATAMART".genre set classification = 'GENRE' where genre_name = '3D Platformer';
update "DATAMART".genre set classification = 'GENRE' where genre_name = '3D Vision';
update "DATAMART".genre set classification = 'PLAYERS' where genre_name = '4 Player Local';
update "DATAMART".genre set classification = '' where genre_name = '4X';
update "DATAMART".genre set classification = '' where genre_name = '6DOF';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = '8-bit Music';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Abstract';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Action';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Action-Adventure';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Action Roguelike';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Action RPG';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Action RTS';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Addictive';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Adventure';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Agriculture';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Aliens';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Alternate History';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Ambient';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'America';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Animation & Modeling';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Anime';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Arcade';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Archery';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Arena Shooter';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Artificial Intelligence';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Assassin';
update "DATAMART".genre set classification = 'HARDWARE' where genre_name = 'Asymmetric VR';
update "DATAMART".genre set classification = 'PLAYERS' where genre_name = 'Asynchronous Multiplayer';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Atmospheric';
update "DATAMART".genre set classification = '' where genre_name = 'ATV';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Audio Production';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Auto Battler';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Automation';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Automobile Sim';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Base Building';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Baseball';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Based On A Novel';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Basketball';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Battle Royale';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Beat ''em up';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Beautiful';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Benchmark';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Bikes';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Birds';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Blood';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'BMX';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Board Game';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Boomer Shooter';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Boss Rush';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Bowling';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Boxing';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Building';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Bullet Hell';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Bullet Time';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Capitalism';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Card Battler';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Card Game';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Cartoon';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Cartoony';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Casual';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Cats';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Character Action Game';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Character Customization';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Chess';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Choices Matter';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Choose Your Own Adventure';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Cinematic';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'City Builder';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Class-Based';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Classic';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Clicker';
update "DATAMART".genre set classification = 'PLAYERS' where genre_name = 'Co-op';
update "DATAMART".genre set classification = 'PLAYERS' where genre_name = 'Co-op Campaign';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Coding';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Cold War';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Collectathon';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Colony Sim';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Colorful';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Combat';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Combat Racing';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Comedy';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Comic Book';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Competitive';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Conspiracy';
update "DATAMART".genre set classification = 'HARDWARE' where genre_name = 'Controller';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Conversation';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Cooking';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Cozy';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Crafting';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Creature Collector';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Cricket';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Crime';
update "DATAMART".genre set classification = 'FUNDING' where genre_name = 'Crowdfunded';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'CRPG';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Cult Classic';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Cute';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Cyberpunk';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Cycling';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Dark';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dark Comedy';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dark Fantasy';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dark Humor';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Dating Sim';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Deckbuilding';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Demons';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Design & Illustration';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Destruction';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Detective';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dice';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Difficult';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dinosaurs';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Diplomacy';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Documentary';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dog';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dragons';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Drama';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Driving';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Dungeon Crawler';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dungeons & Dragons';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dwarf';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Dynamic Narration';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Dystopian ';
update "DATAMART".genre set classification = 'ASSESSMENTS' where genre_name = 'Early Access';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Economy';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Education';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Electronic';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Electronic Music';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Elf';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Emotional';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Epic';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Episodic';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Escape Room';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'eSports';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Experience';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Experimental';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Exploration';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Extraction Shooter';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Faith';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Family Friendly';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Fantasy';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Farming';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Farming Sim';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Fast-Paced';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Feature Film';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Female Protagonist';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Fighting';
update "DATAMART".genre set classification = 'VIEWPOINT' where genre_name = 'First-Person';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Fishing';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Flight';
update "DATAMART".genre set classification = '' where genre_name = 'FMV';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Football (American)';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Football (Soccer)';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Foreign';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Fox';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'FPS';
update "DATAMART".genre set classification = 'FUNDING' where genre_name = 'Free to Play';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Funny';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Futuristic';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Gambling';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Game Development';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'GameMaker';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Games Workshop';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Gaming';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'God Game';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Golf';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Gore';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Gothic';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Grand Strategy';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Great Soundtrack';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Grid-Based Movement';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Gun Customization';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Hack and Slash';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Hacking';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Hand-drawn';
update "DATAMART".genre set classification = 'HARDWARE' where genre_name = 'Hardware';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Heist';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Hentai';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Hero Shooter';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Hex Grid';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Hidden Object';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Historical';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Hobby Sim';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Hockey';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Horror';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Horses';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Hunting';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Idler';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Illuminati';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Immersive';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Immersive Sim';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Indie';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Instrumental Music';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Intentionally Awkward Controls';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Interactive Fiction';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Inventory Management';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Investigation';
update "DATAMART".genre set classification = 'VIEWPOINT' where genre_name = 'Isometric';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Jet';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Job Simulator';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'JRPG';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Jump Scare';
update "DATAMART".genre set classification = 'FUNDING' where genre_name = 'Kickstarter';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'LEGO';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Lemmings';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Level Editor';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'LGBTQ+';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Life Sim';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Linear';
update "DATAMART".genre set classification = 'PLAYER' where genre_name = 'Local Co-Op';
update "DATAMART".genre set classification = 'PLAYER' where genre_name = 'Local Multiplayer';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Logic';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Loot';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Looter Shooter';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Lore-Rich';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Lovecraftian';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Magic';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Mahjong';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Management';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Mars';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Martial Arts';
update "DATAMART".genre set classification = 'PLAYER' where genre_name = 'Massively Multiplayer';
update "DATAMART".genre set classification = 'PLAYER' where genre_name = 'Match 3';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Mature';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Mechs';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Medical Sim';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Medieval';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Memes';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Metroidvania';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Military';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Mini Golf';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Minigames';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Minimalist';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Mining';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'MMORPG';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'MOBA';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Mod';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Moddable';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Modern';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Motocross';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Motorbike';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Mouse only';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Movie';
update "DATAMART".genre set classification = 'PLAYER' where genre_name = 'Multiplayer';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Multiple Endings';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Music';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Music-Based Procedural Generation';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Musou';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Mystery';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Mystery Dungeon';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Mythology';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Narration';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Narrative';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Nature';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Naval';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Naval Combat';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Ninja';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Noir';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Nonlinear';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Nostalgia';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'NSFW';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Nudity';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Offroad';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Old School';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'On-Rails Shooter';
update "DATAMART".genre set classification = 'PLAYER' where genre_name = 'Online Co-Op';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Open World';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Open World Survival Craft';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Otome';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Outbreak Sim';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Parkour';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Parody ';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Party';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Party-Based RPG';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Party Game';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Perma Death';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Philosophical';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Photo Editing';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Physics';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Pinball';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Pirates';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Pixel Graphics';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Platformer';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Point & Click';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Political';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Political Sim';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Politics';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Pool';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Post-apocalyptic';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Precision Platformer';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Procedural Generation';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Programming';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Psychedelic';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Psychological';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Psychological Horror';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Puzzle';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Puzzle Platformer';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'PvE';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'PvP';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Quick-Time Events';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Racing';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Real-Time';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Real-Time with Pause';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Real Time Tactics';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Realistic';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Reboot';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Relaxing';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Remake';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Replay Value';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Resource Management';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Retro';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Rhythm';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Robots';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Rock Music';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Roguelike';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Roguelike Deckbuilder';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Roguelite';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Roguevania';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Romance';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Rome';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'RPG';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'RPGMaker';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'RTS';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Rugby';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Runner';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Sailing';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Sandbox';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Satire';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Sci-fi';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Science';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Score Attack';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Sequel';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Sexual Content';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Shoot ''Em Up';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Shooter';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Shop Keeper';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Short';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Side Scroller';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Silent Protagonist';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Simulation';
update "DATAMART".genre set classification = 'PLAYER' where genre_name = 'Singleplayer';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Skateboarding';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Skating';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Skiing';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Sniper';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Snooker';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Snow';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Snowboarding';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Social Deduction';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Software';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Software Training';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Sokoban';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Solitaire';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Souls-like';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Soundtrack';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Space';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Space Sim';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Spaceships';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Spectacle fighter';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Spelling';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Split Screen';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Sports';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Stealth';
update "DATAMART".genre set classification = 'HARDWARE' where genre_name = 'Steam Machine';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Steampunk';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Story Rich';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Strategy';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Strategy RPG';
update "DATAMART".genre set classification = 'VISUALS' where genre_name = 'Stylized';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Submarine';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Superhero';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Supernatural';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Surreal';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Survival';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Survival Horror';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Swordplay';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Tabletop';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Tactical';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Tactical RPG';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Tanks';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Team-Based';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Tennis';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Text-Based';
update "DATAMART".genre set classification = 'PLAYER' where genre_name = 'Third-Person Shooter';
update "DATAMART".genre set classification = 'VIEWPOINT' where genre_name = 'Third Person';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Thriller';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Time Attack';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Time Management';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Time Manipulation';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Time Travel';
update "DATAMART".genre set classification = 'VIEWPOINT' where genre_name = 'Top-Down';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Top-Down Shooter';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Touch-Friendly';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Tower Defense';
update "DATAMART".genre set classification = '' where genre_name = 'TrackIR';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Trading';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Trading Card Game';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Traditional Roguelike';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Trains';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Transhumanism';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Transportation';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Trivia';
update "DATAMART".genre set classification = 'TOP LEVEL GENRE' where genre_name = 'Turn-Based';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Turn-Based Combat';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Turn-Based Strategy';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Turn-Based Tactics';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Tutorial';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Twin Stick Shooter';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Typing';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Underground';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Underwater';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Unforgiving';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Utilities';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Vampire';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Vehicular Combat';
update "DATAMART".genre set classification = 'SOFTWARE' where genre_name = 'Video Production';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Vikings';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Villain Protagonist';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Violent';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Visual Novel';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Voice Control';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Volleyball';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Voxel';
update "DATAMART".genre set classification = 'HARDWARE' where genre_name = 'VR';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Walking Simulator';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'War';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Wargame';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Warhammer 40K';
update "DATAMART".genre set classification = 'FUNDING' where genre_name = 'Web Publishing';
update "DATAMART".genre set classification = 'FEATURE' where genre_name = 'Well-Written';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Werewolves';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Western';
update "DATAMART".genre set classification = 'MOODS' where genre_name = 'Wholesome';
update "DATAMART".genre set classification = 'GENRE' where genre_name = 'Word Game';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'World War I';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'World War II';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Wrestling';
update "DATAMART".genre set classification = 'THEMES' where genre_name = 'Zombies';
